config/routes.rb
Rails.application.routes.draw do

  resources :bookmarks do
    get "delete", :on => :member
  end

  devise_for :users

  get 'pages/index'
  root "pages#index"

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :user

  validates :url, presence: true
  validates :url, format: {with: URI.regexp}, if: Proc.new {|a| a.url.present?}
  validates :description, presence:  true

  scope :alpha, lambda { order("bookmarks.description, ASC") }

  def self.search(query)

      self.where("description like ?", "%#{query}%" )

  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :bookmarks
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,  :lockable, :zxcvbnable, :confirmable

  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  class ApplicationController < ActionController::Base
    def after_sign_in_path_for(resource)
      request.env['omniauth.origin'] || stored_location_for(resource) || bookmarks_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  # user has to be logged in before they can access their list of bookmarks
  before_action :authenticate_user!

  def index
    # sets variable to show bookmarks created by user
    @search = params[:search]
    @bookmarks = @search ? Bookmark.search(@search) :
        @bookmarks = current_user.bookmarks.order("description ASC")


  end

  def new
    @bookmark = Bookmark.new
  end


  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  def create
    # creates new bookmark that's related to the current signed in user.
    # book_params is the safe parameters that can be passed on
    @bookmark = current_user.bookmarks.build bookmark_params

    if @bookmark.save
      # flash message to display if the bookmark has been saved
      flash[:notice] = "Your bookmark has successfully been saved"
      redirect_to bookmarks_path
    else
      # displays error message to user based on the validations in the bookmark model for the URL field
      flash[:notice] = "Please enter a valid URL"
      render 'new'
    end
  end

  def update
    @bookmark = Bookmark.find(params[:id])

    if @bookmark.update(bookmark_params)
      # flash message to display if the bookmark is updated successfully
      flash[:notice] = "Your bookmark has been updated successfully"
      # redirects to the list of bookmarks that was created or edited by the user
      redirect_to bookmarks_path
    else
      flash[:notice] = "Please enter a valid URL"
      render 'edit'
    end
  end

  def delete
    @bookmark = Bookmark.find(params[:id])
  end

  def destroy
    # finds the bookmark the user wants to delete by the ID number
    @bookmark = Bookmark.find(params[:id]).destroy
    # flash message to display to the user that their bookmark has been deleted
    flash[:notice] = "Your bookmark has been removed successfully"
    # redirects to the list of bookmarks created by the user
    redirect_to bookmarks_path
  end

  private

  def bookmark_params
    # private method to pass a set of safe params through the URL when saving or editing bookmarks
    params.require(:bookmark).permit(:url,:notes, :description)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def header(text)
    content_for(:header) { text.to_s }
  end




end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger" role="alert" id="error_explanation">

      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bookmarks/_form.html.erb
<br>
<%= form_for @bookmark do |f| %>
    <fieldset>
      <div class="form-group">
        <%= f.label :url, class: 'control-label' %>
        <%= f.text_field  :url, class: 'form-control' %>
      </div>

      <div class="form-group ">
        <%= f.label :description, class: 'control-label' %>
        <%= f.text_field :description, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :notes, class: 'control-label' %>
        <%= f.text_area :notes, class: 'form-control' %>

      </div>
    </fieldset>

    <%= f.submit "Submit", class: 'btn btn-primary' %>
    <%= link_to 'Cancel', bookmarks_path, class: 'btn btn-default' %>
<% end %>

<br>

app/views/bookmarks/_search.html.erb
<%= form_tag bookmarks_path, method: 'get' do %>
  <fieldset>
    <%= text_field_tag 'search', @search, placeholder: "Search Bookmarks", size: 35   %>
    <% if params[:search].present? %>
         <%= link_to "clear", bookmarks_path, class: 'btn btn-primary btn-sm' %>
        <br>
       <% else %>
            <button type="submit" class="btn btn-primary btn-sm">
              <span class="glyphicon glyphicon-search"></span>
            </button>

  </fieldset>

        <% end %>
    <% end %>
<br>

app/views/bookmarks/delete.html.erb
<section style="margin-top: -21px;" class="row page_header">
  <div class="container">
    <h3>delete bookmark</h3>
    <ol class="breadcrumb">
      <li><%= link_to 'home', pages_index_path %> </li>
      <li><%= link_to 'my bookmarks', bookmarks_path %></li>
      <li class="active">delete bookmark</li>
    </ol>
  </div>
</section>

<div class="container">
<br>
  <h3>Are you sure you want to delete this bookmark?</h3>

    <p><strong>Bookmark:</strong> <%= @bookmark.description %> </p>
    <p><strong>URL:</strong> <%=	 @bookmark.url %></p>
    <p><strong>Notes:</strong> <%= @bookmark.notes %> </p>

<p>  <%= link_to "Delete Bookmark", bookmark_path(@bookmark), method: "delete", class: 'btn btn-danger' %> <%= link_to "Edit", edit_bookmark_path(@bookmark), class: 'btn btn-primary' %> <%=	 link_to "Cancel", bookmarks_path, class: 'btn btn-default' %> </p>

</div>
<br>

app/views/bookmarks/edit.html.erb
<section style="margin-top: -21px;" class="row page_header">
  <div class="container">
    <h3>my bookmarks</h3>
    <ol class="breadcrumb">
      <li><%= link_to 'home', pages_index_path %> </li>
      <li><%= link_to 'my bookmarks', bookmarks_path %></li>
      <li class="active">edit bookmark</li>
    </ol>
  </div>
</section>

<div class="container">
<% header "Edit Bookmark" %>


<%= render 'form' %>
</div>

app/views/bookmarks/index.html.erb
<section style="margin-top: -21px;" class="row page_header">
  <div class="container">
    <h3>my bookmarks</h3>
    <ol class="breadcrumb">
      <li><%= link_to 'home', pages_index_path %> </li>
      <li class="active">my bookmarks</li>
    </ol>
  </div>
</section>

<div class="container">

<br>
<p><%= link_to("Add Bookmark", new_bookmark_path, class: 'btn btn-primary')  %> </p>
<br>

<%= render 'search' %>


<% if @bookmarks.empty? %>
   <p> <%= "Looks like you don't have any bookmarks. Click the 'Add Bookmark' button above to get started." %> </p>
    <% else %>
    <% end %>

<table class="table">
  <tr>
    <th>Bookmarks</th>
  <th>Notes</th>
  <th></th>
    </tr>
      <%	 @bookmarks.each do |bookmark| %>
      <tr>
        <td> <%= link_to("#{bookmark.description}", bookmark.url) %> </td>
        <td> <%= bookmark.notes %></td>
        <td align="right"> <%= link_to("Edit", edit_bookmark_path(bookmark), class: 'btn btn-primary btn-xs') %>
          <%= link_to "Delete", delete_bookmark_path(bookmark), class: 'btn btn-danger btn-xs'  %>   </td>
      </tr>
      <% end %>
</table>
</div>
<br>
<br>

app/views/bookmarks/new.html.erb
<section style="margin-top: -21px;" class="row page_header">
  <div class="container">
    <h3>my bookmarks</h3>
    <ol class="breadcrumb">
      <li><%= link_to 'home', pages_index_path %> </li>
      <li><%= link_to 'my bookmarks', bookmarks_path %></li>
      <li class="active">add new bookmark</li>
    </ol>
  </div>
</section>

<div class="container">
<%= render 'form' %>
  </div>

app/views/bookmarks/show.html.erb
<h1>Bookmarks#show</h1>
<p>Find me in app/views/bookmarks/show.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="row container-fluid">
  <div class="top_footer row m0">
    <div class="container">
      <div class="row m0 quick_contact">
        <ul class="nav nav-pills">
          <li><a href="tel:7035557890"><i class="lnr lnr-phone"></i>703 - 555 - 7890</a></li>
          <li><a href="mailto:info@gabookmarks.com"><i class="lnr lnr-envelope"></i>info@gabookmarks.com</a></li>
          <li><a href="#"><i class="lnr lnr-bubble"></i>chat with us</a></li>
        </ul>
      </div>
      <div class="row shortKnowledge">
        <div class="col-sm-6 about">
          <h4>GA Bookmarks </h4>
          <p>GA Bookmarks is a US based cloud software company. Our learn and agile team as a wealth of talent and experience. We are focused on creating the best online applications to help creatives manage and grow their business</p>
        </div>
        <div class="col-sm-6 product">
          <h4>Products</h4>
          <ul class="product_list nav">
            <li><a href="#">Mobile Apps</a></li>
            <li><a href="#">GA Task Manager</a></li>
            <li><a href="#">GA Calendar</a></li>
            <li><a href="#">GA Bookmark Manager</a></li>
            <li><a href="#">GA Mail Plugins</a></li>
            <li><a href="#">Other Products</a></li>
          </ul>
        </div>
      </div>
      <div class="row beInContact m0">
        <div class="btn-group country_select">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="flag"> <%= image_tag("icons/footer/flag.png", class: 'img-circle') %> </span>USA<i class="fa fa-chevron-down"></i>
          </button>
          <ul class="dropdown-menu">
            <li><a href="#">India</a></li>
            <li><a href="#">Bangladesh</a></li>
            <li><a href="#">England</a></li>
            <li><a href="#">Africa</a></li>
            <li><a href="#">Australlia</a></li>
          </ul>
        </div>
        <div class="social_icos">
          <ul class="nav">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fa fa-google"></i></a></li>
            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
          </ul>
        </div>
        <div class="subscribe_form" style="padding-left:30px; padding-top: 30px ;">
          <form action="#" class="form-inline">
            <div class="form-group">
              <label>Subscribe<small>Newsletter</small></label>
              <div class="input-group">
                <input type="email" class="form-control" placeholder="Email Address">
                <span class="input-group-addon"><input type="submit" value="Go" class="btn"></span>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="row m0 copyright_line" style="height: 150px;">
    Copyright &copy; 2015 GABookmarks.com. All Rights Reserved
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'GA Bookmarks', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <% if user_signed_in? %>
            <li><%= link_to 'My Bookmarks', bookmarks_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
            <li class="dropdown active">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <%= current_user.name %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Profile', edit_user_registration_path %></li>
                <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
        <% else %>
            <li class="active"><%= link_to 'Log In', new_user_session_path %></li>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookmarks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/js/umd/collapse.js' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <%= csrf_meta_tags %>
</head>
<body>
<!--Begin navigation-->
  <%= render 'layouts/navigation' %>

<!--Renders flash notice messages-->
  <% flash.each do |key, value| %>

      <div style="margin-left: auto; margin-right: auto; margin-bottom: 20px;" class="container alert alert-notice <%= key %> ">
        <p><%= value %></p>
      </div>
    <div style="margin-bottom: -10px;" class="container alert"></div>
  <% end %>
  <!--Begin content-->
  <%= yield %>

  <!--Begin footer-->
  <%= render 'layouts/footer' %>

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookmarks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body class="home">

<%= render 'layouts/navigation' %>


<%= yield :top_content %>

<div class="container">
  <h1><%= yield :header %></h1>

</div>
<%= yield %>

<%= render 'layouts/footer' %>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>

</body>
</html>

app/views/pages/index.html.erb
    <div style="margin-top: -21px;" class="contact_banner jumbotron"  >
      <div class="container" >
        <h1>Welcome!</h1>
        <p>Register to get started.</p>
        <p>
          <%= link_to 'Register', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
        </p>
      </div>
    </div>


<section class="row why_choose" style="margin-top: -50px;">
  <div class="container">
    <div class="row sectionTitle">
      <h5>Why Choose</h5>
      <h2>GA Bookmarks</h2>
    </div>
    <div class="row">
      <div class="col-sm-4 cause2choose">
        <div class="media">
          <div class="media-left"><%=	 image_tag "icons/cause2choose/1.png" %></div>
          <div class="media-body">
            <h4>Bookmark search</h4>
            <p>Easily find the bookmarks with our easy to use search tool</p>
          </div>
        </div>
      </div>
      <div class="col-sm-4 cause2choose">
        <div class="media">
          <div class="media-left"><%= image_tag "icons/cause2choose/2.png" %> </div>
          <div class="media-body">
            <h4>security</h4>
            <p>Built with the latest security standards to protect your data</p>
          </div>
        </div>
      </div>
      <div class="col-sm-4 cause2choose">
        <div class="media">
          <div class="media-left"><%= image_tag "icons/cause2choose/3.png" %> </div>
          <div class="media-body">
            <h4>Bookmark sync</h4>
            <p>Sync your bookmarks no matter what computer you use</p>
          </div>
        </div>
      </div>
      <div class="col-sm-4 cause2choose">
        <div class="media">
          <div class="media-left"><%= image_tag "icons/cause2choose/4.png" %> </div>
          <div class="media-body">
            <h4>Data in the cloud</h4>
            <p>Your bookmarks are stored in the cloud and always accessiblet</p>
          </div>
        </div>
      </div>
      <div class="col-sm-4 cause2choose">
        <div class="media">
          <div class="media-left"><%= image_tag "icons/cause2choose/5.png" %></div>
          <div class="media-body">
            <h4>technical support</h4>
            <p>Contact our support team if you have any technical difficulties</p>
          </div>
        </div>
      </div>
      <div class="col-sm-4 cause2choose">
        <div class="media">
          <div class="media-left"><%= image_tag "icons/cause2choose/6.png" %></div>
          <div class="media-body">
            <h4>Built with Ruby</h4>
            <p>Built with love using Ruby on Rails</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


<section class="row clients">
  <div class="container">
    <div class="row sectionTitle">
      <h5>our partners &amp;</h5>
      <h2>clients</h2>
    </div>
    <div class="row">
      <ul class="nav nav-justified">
        <li><%=	 link_to image_tag("ds.png", class: 'img-circle'), pages_index_path %> </li>
        <li><%=	 link_to image_tag("microsoft.png", class: 'img-circle'), pages_index_path %> </li>
        <li><%=	 link_to image_tag("engadget.png", class: 'img-circle'), pages_index_path %> </li>
        <li><%=	 link_to image_tag("dell.png", class: 'img-circle'), pages_index_path %> </li>
        <li><%=	 link_to image_tag("pepsi.png", class: 'img-circle'), pages_index_path %> </li>
        <li><%=	 link_to image_tag("verge.png", class: 'img-circle'), pages_index_path %> </li>
        <li><%=	 link_to image_tag("techcrunch.png", class: 'img-circle'), pages_index_path %> </li>
      </ul>
    </div>
  </div>
</section>